// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package suppliers

import (
	"github.com/ascenmmo/tcp-server/pkg/api/types"
	"github.com/google/uuid"
)

type requestGameConnectionsSetSendMessage struct {
	Token   string                  `json:"token"`
	Message types.RequestSetMessage `json:"message"`
}

// Formal exchange type, please do not delete.
type responseGameConnectionsSetSendMessage struct{}

type requestGameConnectionsGetMessage struct {
	Token string `json:"token"`
}

type responseGameConnectionsGetMessage struct {
	Messages types.ResponseGetMessage `json:"messages"`
}

type requestGameConnectionsRemoveUser struct {
	Token  string    `json:"token"`
	UserID uuid.UUID `json:"userID"`
}

// Formal exchange type, please do not delete.
type responseGameConnectionsRemoveUser struct{}
