// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package suppliers

type fallbackGameConnections interface {
	SetSendMessage(err error) bool
	GetMessage(err error) bool
	RemoveUser(err error) bool
}
