// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/ascenmmo/tcp-server/pkg/restconnection"
	"github.com/gofiber/fiber/v2"
)

type httpGameConnections struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverGameConnections
	base             restconnection.GameConnections
}

func NewGameConnections(svcGameConnections restconnection.GameConnections) (srv *httpGameConnections) {

	srv = &httpGameConnections{
		base: svcGameConnections,
		svc:  newServerGameConnections(svcGameConnections),
	}
	return
}

func (http *httpGameConnections) Service() *serverGameConnections {
	return http.svc
}

func (http *httpGameConnections) WithLog() *httpGameConnections {
	http.svc.WithLog()
	return http
}

func (http *httpGameConnections) WithErrorHandler(handler ErrorHandler) *httpGameConnections {
	http.errorHandler = handler
	return http
}

func (http *httpGameConnections) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/rest/gameConnections", http.serveBatch)
	route.Post("/api/v1/rest/gameConnections/setSendMessage", http.serveSetSendMessage)
	route.Post("/api/v1/rest/gameConnections/getMessage", http.serveGetMessage)
	route.Post("/api/v1/rest/gameConnections/removeUser", http.serveRemoveUser)
}
