// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/ascenmmo/tcp-server/pkg/restconnection"
	"github.com/ascenmmo/tcp-server/pkg/restconnection/types"
	"github.com/google/uuid"
)

type GameConnectionsSetSendMessage func(ctx context.Context, token string, message types.RequestSetMessage) (err error)
type GameConnectionsGetMessage func(ctx context.Context, token string) (messages types.ResponseGetMessage, err error)
type GameConnectionsRemoveUser func(ctx context.Context, token string, userID uuid.UUID) (err error)

type MiddlewareGameConnections func(next restconnection.GameConnections) restconnection.GameConnections

type MiddlewareGameConnectionsSetSendMessage func(next GameConnectionsSetSendMessage) GameConnectionsSetSendMessage
type MiddlewareGameConnectionsGetMessage func(next GameConnectionsGetMessage) GameConnectionsGetMessage
type MiddlewareGameConnectionsRemoveUser func(next GameConnectionsRemoveUser) GameConnectionsRemoveUser
